### ISSUE TITLE
A model from the wiki crashes the instance generator

### ISSUE THREAD

**Issue by wasowski** [gsdlab/ClaferConfigurator#8]
http://t3-necsis.cs.uwaterloo.ca:8093/?claferFileURL=http://t3-necsis.cs.uwaterloo.ca:8099/clafer/Do_not_Repeat_Yourself!.cfr

This is a bit strange. I think that this is some secondary technicality in the web tools, perhaps caused by a strange file name.  First I was getting an exception, and after reloading the page the choco back end does not generate any instances, while the Alloy backend nicely generates all of them.

EDIT: investigated a bit more; The exception was a red herring. I get it when I press 'Get Instances' before 'Run'. It would be nice to fix (for instance by lazily calling run), but it is certainly not a big problem.

I stil do not understand why I get no instances from Choco, while I get some from Alloy.  Here is another model (a variant of the same way, in a different file name) that has the same problem:

http://t3-necsis.cs.uwaterloo.ca:8093/?claferFileURL=http://t3-necsis.cs.uwaterloo.ca:8099/clafer/Domain_Constraints.cfr

**Comment by mantkiew** [comment]
Just tried it and it worked. Solved.
